name: zone_guard
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  timeago_flutter: ^3.7.0
  image_picker: ^1.1.2
  supabase_flutter: ^1.10.25
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.3
  location: ^6.0.2
  timeago: ^3.6.1

dependency_overrides:
  sign_in_with_apple: ^6.1.1  # Use a newer compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true