name: zone_guard
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  timeago_flutter: ^3.7.0
  image_picker: ^1.1.2
  location: ^5.0.0
  supabase_flutter: ^1.10.25

dependency_overrides:
  sign_in_with_apple: ^6.1.1  # Use a newer compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true